# -*- coding: utf-8 -*-
"""전봇대과제1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7PYcsRhWb59ILUBKLummr-Hi08jzoRL
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5.git
# %cd yolov5
!pip install -r requirements.txt
!pip install -q ultralytics
!wget https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt
!pwd

from google.colab import files
uploaded = files.upload()

import cv2
import matplotlib.pyplot as plt
from ultralytics import YOLO
import numpy as np
from google.colab import files
import io
from PIL import Image
import torch

device='0' if torch.cuda.is_available() else 'cpu'

img=Image.open("자동차사진.jpg")

model=torch.hub.load('.','custom',path='yolov5s.pt',source='local',device=device)

results=model(img)

results.print()
results.show()